[tool.cibuildwheel]
skip = "*-musllinux*"
environment = { VCPKG_INSTALLATION_ROOT = "/project/vcpkg" }

[tool.cibuildwheel.linux]
before-build = """
            yum install -y curl zip unzip tar
            yum install -y perl-IPC-Cmd
            yum install -y ninja-build
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg update
            """
archs = "x86_64"

[tool.cibuildwheel.windows]
before-build = """
            git clone https://github.com/microsoft/vcpkg
            .\\vcpkg\\bootstrap-vcpkg.bat
            """
archs = "AMD64"

[tool.cibuildwheel.macos]
archs = "universal2"