[tool.cibuildwheel]
skip = "*-musllinux*"
test-requires = "pytest"
test-command = [
            "pwd {project}",
            "ls {project}",
            "pwd {package}",
            "ls {package}",
            "pytest {package}/tests"
            ]

[tool.cibuildwheel.linux]
before-build = """
            yum install -y curl zip unzip tar
            yum install -y perl-IPC-Cmd
            yum install -y ninja-build
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            """
environment = { VCPKG_INSTALLATION_ROOT = "{project}/vcpkg" }

[tool.cibuildwheel.windows]
before-build = """
            cd C:\\
            git clone https://github.com/microsoft/vcpkg
            .\\vcpkg\\bootstrap-vcpkg.bat
            """
environment = { VCPKG_INSTALLATION_ROOT = "C:\\vcpkg" }

[tool.cibuildwheel.macos]

environment = {VCPKG_INSTALLATION_ROOT="/Users/runner/work/build-wheels/build-wheels/vcpkg"}

