[tool.cibuildwheel]
skip = "*-musllinux*"

[tool.cibuildwheel.linux]
before-build = """
            yum install -y curl zip unzip tar
            yum install -y perl-IPC-Cmd
            yum install -y ninja-build
            pwd
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg update
            """
environment = { VCPKG_INSTALLATION_ROOT = "/vcpkg" }
archs = "x86_64"

[tool.cibuildwheel.windows]
before-build = """
            cd C:\\
            git clone https://github.com/microsoft/vcpkg
            .\\vcpkg\\bootstrap-vcpkg.bat
            """
environment = { VCPKG_INSTALLATION_ROOT = "C:\\vcpkg" }
archs = "AMD64"

[tool.cibuildwheel.macos]
before-build = """
            pwd
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg update
            """
environment = { VCPKG_INSTALLATION_ROOT = "/vcpkg" }
archs = "universal2"