[tool.cibuildwheel]
skip = "*-musllinux*"
environment = {VCPKG_INSTALLATION_ROOT="/project/vcpkg"}

[tool.cibuildwheel.linux]
before-all = """
            yum install -y curl zip unzip tar
            yum install -y perl-IPC-Cmd
            yum install -y ninja-build
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            chmod -R 777 vcpkg
            ./vcpkg/vcpkg update
            """
archs = "x86_64"

[tool.cibuildwheel.windows]
archs = "AMD64"

[tool.cibuildwheel.macos]
archs = "universal2"