[tool.cibuildwheel]
skip = "*-musllinux*"

[tool.cibuildwheel.linux]
before-build = """
            yum install -y curl zip unzip tar
            yum install -y perl-IPC-Cmd
            yum install -y ninja-build
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg update
            """
environment = { VCPKG_INSTALLATION_ROOT = "{project}/vcpkg" }

[tool.cibuildwheel.windows]
before-build = """
            cd C:\\
            git clone https://github.com/microsoft/vcpkg
            .\\vcpkg\\bootstrap-vcpkg.bat
            """
environment = { VCPKG_INSTALLATION_ROOT = "C:\\vcpkg" }

[tool.cibuildwheel.macos]
before-build = """
            git clone https://github.com/microsoft/vcpkg
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg update
            """
environment = { VCPKG_INSTALLATION_ROOT = "/Users/runner/work/build-wheels/build-wheels/vcpkg" }