name: lightglue

on:
  workflow_dispatch:
    inputs:
      lightglueVersion:
        description: "LightGlue version"
        required: true
        default: "0.1.0"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD: "cp310-* cp311-*"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.3

      - name: Download LightGlue repository
        run: git clone https://github.com/cvg/LightGlue.git lightglue

      - name: Set version in Linux
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          sed -i 's/^version = ".*"/version = "${{ inputs.lightglueVersion }}"/' lightglue/pyproject.toml

      - name: Patch to include Python3.12+ in MacOS
        if: ${{ matrix.os == 'macos-13' ||  matrix.os == 'macos-latest'}}
        run: |
          sed -i '' 's/^version = ".*"/version = "${{ inputs.lightglueVersion }}"/' lightglue/pyproject.toml

      - name: Patch to include Python3.12+ in Windows
        if: ${{ matrix.os == 'windows-latest'}}
        run: |
          powershell -command "(Get-Content lightglue\\pyproject.toml) -replace 'version = \"0.0\"', 'version = \"${{ inputs.lightglueVersion }}\"' | Set-Content lightglue\\pyproject.toml"

      - name: Build wheels
        run: |
          cd lightglue
          python -m cibuildwheel --output-dir ../wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels to pypi.scm.io
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Get wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish to pypy.scm.io
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_SCM_USERNAME }}
          password: ${{ secrets.PYPI_SCM_PASSWORD }}
          repository-url: https://pypi.scm.io/simple/
          skip-existing: true
