name: pylibCZIrw

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
      CIBW_VERSION: "2.12.3"
      PYLIBCZIRW_VERSION: "3.4.0"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download pylibCZIrw
        run: |
          curl -o pypi.json "https://pypi.org/pypi/pylibczirw/${PYLIBCZIRW_VERSION}/json"
          URL=$(python -c "import json, sys; print([u for u in json.load(sys.stdin)['urls'] if u['url'].endswith('.tar.gz')][0]['url'])" < pypi.json)
          curl -o pylibCZIrw.tar.gz $URL
          tar -xvf pylibCZIrw.tar.gz
          mv pylibCZIrw-${PYLIBCZIRW_VERSION} pylibCZIrw

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==${CIBW_VERSION}

      - name: Fix cmake for Mac
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sed -i '' 's/CMAKE_OSX_DEPLOYMENT_TARGET "10.9"/CMAKE_OSX_DEPLOYMENT_TARGET "12.0"/g' pylibCZIrw/CMakeLists.txt 

      - name: Build wheels
        env:
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS_MACOS: "universal2"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
        run: |
          cd pylibCZIrw
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./pylibCZIrw/wheelhouse/*.whl